GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'geojit123' WITH GRANT OPTION;
create database fliplite;
create user fliplite identified by 'fliplite';
grant all privileges on fliplite.* to fliplite;
create database fliplitelog;
create user fliplitelog identified by 'fliplitelog';
grant all privileges on fliplitelog.* to fliplitelog;
GRANT EXECUTE ON `fliplitelog`.* TO 'fliplite';
create database marketsummary;
create user marketsummary identified by 'marketsummary';
grant all privileges on marketsummary.* to marketsummary;
create database quickfix;
create user quickfix identified by 'quickfix';
grant all privileges on quickfix.* to quickfix;
create database flipspan;
create user flipspan identified by 'flipspan';
grant all privileges on flipspan.* to flipspan;
grant execute on fliplite.* to flipspan;
create database flipspannew;
create user flipspannew identified by 'flipspannew';
grant all privileges on flipspannew.* to flipspannew;
create database quickfixmcxsx;
create user quickfixmcxsx identified by 'quickfixmcxsx';
grant all privileges on quickfixmcxsx.* to quickfixmcxsx;